# Generated by Django 5.0.4 on 2024-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poliza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poliza", models.CharField(max_length=20)),
                ("asegurado", models.CharField(max_length=200)),
                ("fecha", models.DateField()),
            ],
        ),
    ]
