# Generated by Django 5.0.4 on 2024-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poliza",
            name="CUIT",
            field=models.CharField(default="20-34123456-7", max_length=20),
        ),
    ]
