# Generated by Django 5.0.4 on 2024-05-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificados", "0003_alter_poliza_cuit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("CUIL", models.CharField(max_length=20)),
                (
                    "id_poliza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certificados.poliza",
                    ),
                ),
            ],
        ),
    ]
